# vim: ts=2 sw=2 et

title: "Hunting the Shmoo"
baseURL: "https://ahal.ca/"
copyright: "© 2018 Andrew Halberstadt"

languageCode: "en-us"
theme: "hugo-theme-bootstrap4-blog"
disqusShortname: "ahal"

paginate: 10
sectionPagesMenu: "navbar"

permalinks:
  blog: "/blog/:year/:slug/"
  page: "/:slug/"


menu:
  #sidebar:
    #- name: "Link 1"
    #  url: "https://example.com"
    #- name: "Link 2"
    #  url: "https://example.org"

  navbar:
    - identifier: blog
      name: Blog
      url: /blog/

# Theme variables
params:
  author: "Andrew Halberstadt"
  description: "Ramblings related to my work at Mozilla and other projects."
  date_format: "Jan 02, 2006"
  sidebar:
    num_recent_posts: 10
    tag_cloud: true
  social:
    mastodon: "ahal@mastodon.club"
    twitter: "halbersa"
  #staticman:
    #stbaseurl: "https://api.staticman.net/v2/entry"
    #stuser: "ahal"
    #strepo: "hunting-the-shmoo"
    #stbranch: "master"

PygmentsCodeFences: true
PygmentsStyle: "monokai"
PygmentsOptions:
  linenos: table
