# vim: ts=2 sw=2 et

title: "Hunting the Shmoo"
baseURL: "https://ahal.ca/"
copyright: "© 2018 Andrew Halberstadt"

languageCode: "en-us"
theme: "hugo-theme-bootstrap4-blog"

paginate: 10
sectionPagesMenu: "navbar"

permalinks:
  blog: "/blog/:year/:slug/"
  casts: "/casts/:year/:slug/"
  page: "/:slug/"


menu:
  #sidebar:
    #- name: "Link 1"
    #  url: "https://example.com"
    #- name: "Link 2"
    #  url: "https://example.org"

  navbar:
    - identifier: blog
      name: Blog
      url: /blog/

    - identifier: casts
      name: Casts
      url: /casts/

taxonomies:
  series: series
  tag: tags

# Theme variables
params:
  author: "Andrew Halberstadt"
  description: "Screencasts and blog posts on workflow, productivity, tools, Mozilla and whatever else tickles my fancy."
  date_format: "Jan 02, 2006"
  mainSections:
    - blog
    - casts
  sidebar:
    num_recent_posts: 10
    tag_cloud: true
  social:
    mastodon: "ahal@mastodon.club"
    twitter: "halbersa"
  # Whether to display summaries on the list page
  truncate: true

PygmentsCodeFences: true
PygmentsStyle: "monokai"
PygmentsOptions:
  linenos: table
